## Carga inicial

### Utilizar la clase GestorDatos

### Archivos de diferentes fechas que comparten estructura, para combinarlos

In [1]:
from src.datos.Gestor_Datos import GestorDatos
# Crear instancia del gestor de datos
gestor = GestorDatos(ruta_base="../data")

# Verificar rutas disponibles
print("Carpeta RAW:", gestor.ruta_raw)
print("Carpeta PROCESSED:", gestor.ruta_processed)

# Combinar archivos del 2025 y 2026
df_combinado = gestor.combinar_datos_por_anio("2c.txt", "Cuadro_1_llegadas_todas_las_vias_2026.txt")

# Mostrar las primeras filas del resultado
df_combinado.head()

Carpeta RAW: ../data\raw
Carpeta PROCESSED: ../data\processed
TXT convertido a CSV → ../data\processed\2c.csv
Archivo cargado: 2c.txt (83 filas, 14 columnas)
Datos limpiados: valores nulos o vacíos reemplazados por 0.
TXT convertido a CSV → ../data\processed\Cuadro_1_llegadas_todas_las_vias_2026.csv
Archivo cargado: Cuadro_1_llegadas_todas_las_vias_2026.txt (83 filas, 4 columnas)
Datos limpiados: valores nulos o vacíos reemplazados por 0.
Archivos 2025 y 2026 combinados correctamente.

,Zona_Pais,01-2025,02-2025,03-2025,04-2025,05-2025,06-2025,07-2025,08-2025,09-2025,10-2025,11-2025,12-2025,01-2026,02-2026,Total_2025,Total_2026,Total
79,TOTAL,298475.0,293784.0,336476.0,252867.0,205803.0,232571.0,262048.0,199959.0,121815.0,145663.0,247387.0,347143.0,321992.0,331967.0,2943991.0,653959.0,3597950.0
3,AMERICA DEL NORTE,202581.0,199882.0,247595.0,171151.0,149633.0,177467.0,179300.0,124758.0,69698.0,85817.0,157377.0,234341.0,224641.0,230248.0,1999600.0,454889.0,2454489.0
16,CANADA,42440.0,39843.0,38851.0,23193.0,11508.0,8996.0,12551.0,10399.0,5144.0,9703.0,28897.0,42556.0,51655.0,52221.0,274081.0,103876.0,377957.0
29,ESTADOS UNIDOS,154170.0,153380.0,200831.0,138949.0,130004.0,161583.0,156348.0,104920.0,57064.0,69581.0,119833.0,181144.0,165662.0,171365.0,1627807.0,337027.0,1964834.0
49,MEXICO,5971.0,6659.0,7913.0,9009.0,8121.0,6888.0,10401.0,9439.0,7490.0,6533.0,8647.0,10641.0,7324.0,6662.0,97712.0,13986.0,111698.0

### Exportar datos que se combinaron a Processed

In [2]:
# Exportar el DataFrame combinado
gestor.exportar_datos(df_combinado, "turismo_combinado_2025_2026.csv")

Archivo exportado correctamente en: ../data\processed\turismo_combinado_2025_2026.csv

### Para archivos individuales

In [3]:
# Procesar archivo individual
df_hist = gestor.procesar_archivo_individual("TurismoHistorico.txt")

# Ver primeras filas
df_hist.head()

TXT convertido a CSV → ../data\processed\TurismoHistorico.csv
Archivo cargado: TurismoHistorico.txt (183 filas, 10 columnas)
Datos limpiados: valores nulos o vacíos reemplazados por 0.
Archivo exportado correctamente en: ../data\processed\TurismoHistorico_procesado.csv
Archivo individual procesado y exportado como: TurismoHistorico_procesado.csv

,Ano,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Total,2 959 869,3 016 667,3 139 008,1 011 912,1 347 055,2 349 537,2 751 134,2 919 483,2 943 991
1,América del norte,1 507 945,1 580 991,1 666 571,571 010,958 792,1 533 502,1 820 038,1 989 725,1 999 600
2,Canadá,201 921,217 006,234 621,115 632,53 185,183 678,260 744,272 256,274 081
3,Estados Unidos,1 199 241,1 265 067,1 334 777,434 775,868 986,1 290 038,1 473 620,1 621 340,1 627 807
4,México,106 783,98 918,97 173,20 603,36 621,59 786,85 674,96 129,97 712

In [4]:
gestor.exportar_datos(df_hist, "TurismoHistorico_procesado.csv")

Archivo exportado correctamente en: ../data\processed\TurismoHistorico_procesado.csv